- name: Copy local files (private key + new inventory) to mgmt node
  hosts: mgmtnode
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
    - name: Wipe known_hosts entirely on local
      delegate_to: localhost
      run_once: true
      shell: "truncate -s 0 ~/.ssh/known_hosts"
      become: false

    - name: Copy private key from LOCAL to mgmt node
      ansible.builtin.copy:
        src: "{{ lookup('env','HOME') }}/.ssh/ansible_ed25519"
        dest: /home/almalinux/.ssh/ansible_ed25519
        owner: almalinux
        group: almalinux
        mode: '0600'


