- name: Copy local files (private key + new inventory) to mgmt node
  hosts: mgmtnode
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
    - name: Remove old known_hosts entry for mgmt IP (if previously used)
      local_action:
        module: shell
        cmd: ssh-keygen -R {{ ansible_host }}
      run_once: true
      delegate_to: localhost
      become: false

    - name: Copy private key from LOCAL to mgmt node
      ansible.builtin.copy:
        src: "{{ lookup('env','HOME') }}/.ssh/ansible_ed25519"
        dest: /home/almalinux/.ssh/ansible_ed25519
        owner: almalinux
        group: almalinux
        mode: '0600'

    - name: Copy updated inventory.json to mgmt node
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../ansible/inventories/inventory.json"
        dest: /home/almalinux/data-pipeline/ansible/inventories/inventory.json
        owner: almalinux
        group: almalinux
        mode: '0644'
