- name: Copy local files (private key + new inventory) to mgmt node
  hosts: mgmtnode
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
    - name: Remove old known_hosts entry for mgmt IP (if previously used)
      local_action:
        module: shell
        # Overwrite the default known_hosts file if you need a specific location:
        # cmd: ssh-keygen -R {{ ansible_host }} -f /home/almalinux/.ssh/known_hosts
        cmd: ssh-keygen -R {{ ansible_host }}
      run_once: true
      delegate_to: localhost
      become: false   # <--- TURN OFF BECOME for this local action

    - name: Copy private key from LOCAL to mgmt node
      ansible.builtin.copy:
        src: "{{ lookup('env','HOME') }}/.ssh/ansible_ed25519"
        dest: /home/almalinux/.ssh/ansible_ed25519
        owner: almalinux
        group: almalinux
        mode: '0600'

    - name: Ensure data-pipeline/ansible/inventories directory is correct
      file:
        path: /home/almalinux/data-pipeline/ansible/inventories
        state: directory
        owner: almalinux
        group: almalinux
        mode: '0755'
        recurse: true

    - name: Copy updated inventory.json to mgmt node
      copy:
        src: "{{ playbook_dir }}/../../ansible/inventories/inventory.json"
        dest: /home/almalinux/data-pipeline/ansible/inventories/inventory.json
        owner: almalinux
        group: almalinux
        mode: '0644'
