- name: Update mgmt node inventory
  hosts: mgmtnode
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
    - name: Wipe known_hosts entirely on local
      delegate_to: localhost
      run_once: true
      shell: "truncate -s 0 ~/.ssh/known_hosts"
      become: false

    - name: Copy private key from LOCAL to mgmt node
      ansible.builtin.copy:
        src: "{{ lookup('env','HOME') }}/.ssh/ansible_ed25519"
        dest: /home/almalinux/.ssh/ansible_ed25519
        owner: almalinux
        group: almalinux
        mode: '0600'

    - name: Check if data-pipeline repo has finished downloading
      become_user: almalinux
      ansible.builtin.stat:
        path: /home/almalinux/data-pipeline/ansible/inventories
      register: repo_folder

    - name: Wait for data-pipeline directory to appear (retry a few times)
      become_user: almalinux
      pause:
        seconds: 5
      until: repo_folder.stat.exists
      retries: 10
      delay: 5
      fail_msg: "data-pipeline/ansible/inventories folder never appeared on the mgmt node."

    - name: Copy updated inventory.json to mgmt node
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../ansible/inventories/inventory.json"
        dest: /home/almalinux/data-pipeline/ansible/inventories/inventory.json
        owner: almalinux
        group: almalinux
        mode: '0644'
