- name: Update mgmt node inventory
  hosts: mgmtnode
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:
    - name: Wipe known_hosts entirely on local
      delegate_to: localhost
      run_once: true
      shell: "truncate -s 0 ~/.ssh/known_hosts"
      become: false

    - name: Copy private key from LOCAL to mgmt node
      ansible.builtin.copy:
        src: "{{ lookup('env','HOME') }}/.ssh/ansible_ed25519"
        dest: /home/almalinux/.ssh/ansible_ed25519
        owner: almalinux
        group: almalinux
        mode: '0600'

    - name: Copy new inventory.json to /tmp on mgmt node
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../ansible/inventories/inventory.json"
        dest: /tmp/inventory.json
        mode: '0644'
        force: yes

    - name: Move inventory.json into final location under almalinux
      become_user: almalinux
      shell: "mv /tmp/inventory.json /home/almalinux/data-pipeline/ansible/inventories/inventory.json"
