---
- name: Setup Monitoring and Logging on All Hosts
  hosts: all
  become: yes
  vars:
    grafana_domain: "grafana.ds4eng.condenser.arc.ucl.ac.uk"
    prometheus_domain: "prometheus.ds4eng.condenser.arc.ucl.ac.uk"
    certbot_email: "ucabbaa@ucl.ac.uk"  # Replace with your email

  tasks:
    #### Enable EPEL repository
    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    #### Install firewalld, python3-pip, and python3-firewall
    - name: Install firewalld, python3-pip, and python3-firewall
      yum:
        name:
          - firewalld
          - python3-pip
          - python3-firewall
        state: present

    #### Ensure firewalld is running and enabled
    - name: Ensure firewalld is running and enabled
      systemd:
        name: firewalld
        state: started
        enabled: yes

    #### Install Prometheus Node Exporter
    - name: Install Prometheus Node Exporter
      block:
        - name: Download Node Exporter binary
          get_url:
            url: "https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz"
            dest: "/tmp/node_exporter.tar.gz"
            mode: '0644'
            force: yes  # Force re-download to ensure we have the correct file

        - name: Extract Node Exporter
          unarchive:
            src: "/tmp/node_exporter.tar.gz"
            dest: "/usr/local/bin/"
            remote_src: yes
            extra_opts: [--strip-components=1]

        - name: Ensure Node Exporter binary is executable
          file:
            path: /usr/local/bin/node_exporter
            owner: root
            group: root
            mode: '0755'

        - name: Create Node Exporter service
          copy:
            dest: /etc/systemd/system/node_exporter.service
            content: |
              [Unit]
              Description=Node Exporter
              After=network.target

              [Service]
              User=root
              ExecStart=/usr/local/bin/node_exporter
              Restart=always

              [Install]
              WantedBy=multi-user.target
            owner: root
            group: root
            mode: '0644'

        - name: Reload systemd daemon for Node Exporter
          systemd:
            daemon_reload: yes

        - name: Start and enable Node Exporter service
          systemd:
            name: node_exporter
            state: started
            enabled: yes

    #### Configure Firewall to Allow Node Exporter Port (9100)
    - name: Open port 9100 in firewalld
      firewalld:
        port: 9100/tcp
        permanent: yes
        state: enabled

    - name: Reload firewalld to apply changes
      service:
        name: firewalld
        state: reloaded

- name: Install and Configure Prometheus on Control Node
  hosts: localhost
  become: yes
  vars:
    grafana_domain: "grafana.ds4eng.condenser.arc.ucl.ac.uk"
    prometheus_domain: "prometheus.ds4eng.condenser.arc.ucl.ac.uk"
    certbot_email: "ucabbaa@ucl.ac.uk"  

  tasks:
    - name: Create Prometheus user and group
      user:
        name: prometheus
        system: yes
        shell: /sbin/nologin

    - name: Download Prometheus binary
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v2.47.0/prometheus-2.47.0.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"
        mode: '0644'
        force: yes

    - name: Create /tmp/prometheus directory
      file:
        path: /tmp/prometheus
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/tmp/prometheus/"
        remote_src: yes
        extra_opts: ['--strip-components=1']

    - name: Move Prometheus binaries to /usr/local/bin/
      copy:
        src: "/tmp/prometheus/prometheus"
        dest: "/usr/local/bin/prometheus"
        remote_src: yes
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Move Prometheus promtool binary to /usr/local/bin/
      copy:
        src: "/tmp/prometheus/promtool"
        dest: "/usr/local/bin/promtool"
        remote_src: yes
        owner: prometheus
        group: prometheus
        mode: '0755'

    # Create Prometheus directories before copying consoles and console_libraries
    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /var/lib/prometheus
        - /etc/prometheus

    - name: Move Prometheus consoles directory
      copy:
        src: "/tmp/prometheus/consoles"
        dest: "/etc/prometheus/consoles"
        remote_src: yes
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Move Prometheus console_libraries directory
      copy:
        src: "/tmp/prometheus/console_libraries"
        dest: "/etc/prometheus/console_libraries"
        remote_src: yes
        owner: prometheus
        group: prometheus
        mode: '0755'

    - name: Set ownership and permissions for /etc/prometheus/consoles
      file:
        path: /etc/prometheus/consoles
        owner: prometheus
        group: prometheus
        mode: '0755'
        recurse: yes

    - name: Set ownership and permissions for /etc/prometheus/console_libraries
      file:
        path: /etc/prometheus/console_libraries
        owner: prometheus
        group: prometheus
        mode: '0755'
        recurse: yes

    - name: Generate Prometheus configuration file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          alerting:
            alertmanagers:
              - static_configs:
                  - targets: ['localhost:9093']

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'node_exporter'
              static_configs:
                - targets:
                    {% for host in groups['all'] %}
                      - '{{ hostvars[host].ansible_default_ipv4.address }}:9100'
                    {% endfor %}
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Set ownership of Prometheus binaries
      file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
      loop:
        - /usr/local/bin/prometheus
        - /usr/local/bin/promtool

    - name: Deploy Prometheus Alert Rules
      include_role:
        name: prometheus_alerts

    - name: Create Prometheus service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Service
          After=network.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target
        owner: prometheus
        group: prometheus
        mode: '0644'

    - name: Reload systemd daemon for Prometheus
      systemd:
        daemon_reload: yes

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

    # Configure Firewall to Allow Prometheus Port (9090)
    - name: Open port 9090 in firewalld
      firewalld:
        port: 9090/tcp
        permanent: yes
        state: enabled

    - name: Reload firewalld to apply changes
      service:
        name: firewalld
        state: reloaded

- name: Install and Configure Grafana on Control Node
  hosts: localhost
  become: yes
  vars:
    grafana_domain: "grafana.ds4eng.condenser.arc.ucl.ac.uk"
    prometheus_domain: "prometheus.ds4eng.condenser.arc.ucl.ac.uk"
    certbot_email: "ucabbaa@ucl.ac.uk"  

  tasks:
    - name: Add Grafana repository
      yum_repository:
        name: grafana
        description: Grafana Repository
        baseurl: https://packages.grafana.com/oss/rpm
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://packages.grafana.com/gpg.key
        enabled: yes

    - name: Install Grafana
      yum:
        name: grafana
        state: present

    - name: Install initscripts package (for systemd-sysv-install)
      yum:
        name: initscripts
        state: present

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Ensure Grafana directories have correct ownership
      file:
        path: "{{ item }}"
        state: directory
        owner: grafana
        group: grafana
        recurse: yes
      loop:
        - /var/lib/grafana
        - /var/log/grafana
        - /etc/grafana

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Fetch Grafana service logs
      shell: journalctl -u grafana-server -b --no-pager
      register: grafana_logs
      ignore_errors: yes

    - name: Display Grafana service logs
      debug:
        var: grafana_logs.stdout

    - name: Verify default Grafana service file exists
      stat:
        path: /usr/lib/systemd/system/grafana-server.service
      register: default_grafana_service

    - name: Debug default Grafana service file status
      debug:
        msg: "Default Grafana service file exists: {{ default_grafana_service.stat.exists }}"

    - name: Create Grafana provisioning directories for dashboards
      file:
        path: /etc/grafana/provisioning/dashboards
        state: directory
        owner: grafana
        group: grafana
        mode: '0755'

    - name: Replace datasource placeholder in cw.json
      replace:
        path: "{{ playbook_dir }}/../dashboard/cw.json"
        regexp: '\$\{datasource\}'
        replace: 'prometheus'

    - name: Copy Dashboard JSON
      copy:
        src: "{{ playbook_dir }}/../dashboard/cw.json"
        dest: /etc/grafana/provisioning/dashboards/cw.json
        owner: grafana
        group: grafana
        mode: '0644'
      notify: Restart Grafana

    - name: Create Dashboard Provisioning YAML
      copy:
        dest: /etc/grafana/provisioning/dashboards/dashboards.yml
        content: |
          apiVersion: 1

          providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              options:
                path: /etc/grafana/provisioning/dashboards
        owner: grafana
        group: grafana
        mode: '0644'

    - name: Create Grafana provisioning directories for datasources
      file:
        path: /etc/grafana/provisioning/datasources
        state: directory
        owner: grafana
        group: grafana
        mode: '0755'

    - name: Copy Prometheus Data Source Provisioning
      copy:
        src: "{{ playbook_dir }}/../datasource/prometheus.yml"
        dest: /etc/grafana/provisioning/datasources/prometheus.yml
        owner: grafana
        group: grafana
        mode: '0644'

    - name: Set Grafana admin user
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: '^admin_user'
        line: 'admin_user = admin'
      notify: Restart Grafana

    - name: Set Grafana admin password
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: '^admin_password'
        line: 'admin_password = admin'
      notify: Restart Grafana

    #### Install and Configure Nginx as Reverse Proxy
    - name: Install Certbot Nginx plugin
      yum:
        name: python3-certbot-nginx
        state: present

    - name: Obtain SSL certificate for Grafana
      command: >
        certbot --nginx --non-interactive --agree-tos
        -m "{{ certbot_email }}"
        -d "{{ grafana_domain }}"
      args:
        creates: "/etc/letsencrypt/live/{{ grafana_domain }}/fullchain.pem"

    - name: Obtain SSL certificate for Prometheus
      command: >
        certbot --nginx --non-interactive --agree-tos
        -m "{{ certbot_email }}"
        -d "{{ prometheus_domain }}"
      args:
        creates: "/etc/letsencrypt/live/{{ prometheus_domain }}/fullchain.pem"

    - name: Configure Nginx for Grafana
      copy:
        dest: "/etc/nginx/conf.d/grafana.conf"
        content: |
          server {
              listen 80;
              server_name {{ grafana_domain }};
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name {{ grafana_domain }};

              ssl_certificate /etc/letsencrypt/live/{{ grafana_domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ grafana_domain }}/privkey.pem;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify: Reload Nginx

    - name: Configure Nginx for Prometheus
      copy:
        dest: "/etc/nginx/conf.d/prometheus.conf"
        content: |
          server {
              listen 80;
              server_name {{ prometheus_domain }};
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name {{ prometheus_domain }};

              ssl_certificate /etc/letsencrypt/live/{{ prometheus_domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ prometheus_domain }}/privkey.pem;

              location / {
                  proxy_pass http://localhost:9090;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify: Reload Nginx

    #### Configure Firewall
    - name: Allow HTTP and HTTPS through firewalld
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - http
        - https
      notify: Reload firewalld

    - name: Close direct access to Prometheus and Grafana ports
      firewalld:
        port: "{{ item }}/tcp"
        state: disabled
        permanent: yes
      loop:
        - 9090
        - 3000
      notify: Reload firewalld

  handlers:
    - name: Restart Grafana
      systemd:
        name: grafana-server
        state: restarted

    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded

    - name: Reload firewalld
      systemd:
        name: firewalld
        state: reloaded
