# /home/almalinux/ansible/playbooks/run_pipeline.yml

---
- name: Distribute and Run Data Analysis Pipeline via Celery
  hosts: host
  become: yes
  vars:
    batch_size: 100
    datasets:
      - organism: "test"
        data_input_dir: "/mnt/datasets/test/"
        results_dir: "/mnt/results/test/"
      #- organism: "ecoli"
      #  data_input_dir: "/mnt/datasets/ecoli_proteome/"
      #  results_dir: "/mnt/results/ecoli/"
  tasks:
    - name: Find all .pdb files for each dataset
      find:
        paths: "{{ item.data_input_dir }}"
        patterns: "*.pdb"
      register: pdb_files
      loop: "{{ datasets }}"
      loop_control:
        label: "{{ item.organism }}"

    - name: Set fact for datasets and their PDB files
      set_fact:
        datasets_pdb: "{{ datasets_pdb | default([]) + [ {
          'organism': item.item.organism,
          'results_dir': item.item.results_dir,
          'data_input_dir': item.item.data_input_dir,
          'files': item.files | map(attribute='path') | list
        } ] }}"
      loop: "{{ pdb_files.results }}"
      loop_control:
        label: "{{ item.item.organism }}"

    - name: Limit each dataset to batch_size .pdb files
      set_fact:
        datasets_pdb_limited: "{{ datasets_pdb_limited | default([]) + [ {
          'organism': item.organism,
          'results_dir': item.results_dir,
          'data_input_dir': item.data_input_dir,
          'files': (item.files | list)[0:batch_size]
        } ] }}"
      loop: "{{ datasets_pdb }}"
      loop_control:
        label: "{{ item.organism }}"

    - name: Enqueue pipeline tasks for each dataset
      debug:
        msg: "Dispatching tasks for organism: {{ item.organism }}"
      loop: "{{ datasets_pdb_limited }}"
      loop_control:
        label: "{{ item.organism }}"

    - name: Dispatch tasks via Celery
      shell: |
        python3 /opt/data_pipeline/dispatch_tasks.py "{{ item.data_input_dir }}" "{{ item.results_dir }}" "{{ item.organism }}"
      loop: "{{ datasets_pdb_limited }}"
      loop_control:
        label: "{{ item.organism }}"
      when: item.files | length > 0
