- name: Uncompress .pdb.gz and .cif.gz Files Using pigz
  hosts: storage
  become: yes
  vars:
    datasets_dirs:
      - /mnt/datasets/human_proteome
      - /mnt/datasets/ecoli_proteome
    parallel_jobs: 4  

  tasks:
    - name: Find compressed files first
      find:
        paths: "{{ dataset_dir }}"
        patterns:
          - "*.pdb.gz"
          - "*.cif.gz"
        recurse: yes
      register: gz_files
      loop: "{{ datasets_dirs }}"
      loop_control:
        loop_var: dataset_dir
        index_var: idx

    - name: Uncompress files directly using find and xargs if any found
      shell: |
        find {{ dataset_dir }} -type f \( -name '*.pdb.gz' -o -name '*.cif.gz' \) -print0 | xargs -0 -n 1 -P {{ parallel_jobs }} pigz -d -f
      when: gz_files.results[idx].matched > 0
      loop: "{{ datasets_dirs }}"
      loop_control:
        loop_var: dataset_dir
        index_var: idx
      args:
        executable: /bin/bash

    - name: Verify uncompression by counting original files
      find:
        paths: "{{ dataset_dir }}"
        patterns:
          - "*.pdb"
          - "*.cif"
        recurse: yes
        file_type: file
      register: original_files
      loop: "{{ datasets_dirs }}"
      loop_control:
        loop_var: dataset_dir
        index_var: idx

    - name: Debug - Number of uncompressed files
      debug:
        msg: "Total number of uncompressed files in {{ dataset_dir }}: {{ original_files.results[idx].matched }}"
      loop: "{{ datasets_dirs }}"
      loop_control:
        loop_var: dataset_dir
        index_var: idx
