# roles/flower/tasks/main.yml

- name: Install Flower
  pip:
    name: flower
    state: present

- name: Deploy Flower systemd Service File
  template:
    src: flower.service.j2
    dest: /etc/systemd/system/flower.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon for Flower
  systemd:
    daemon_reload: yes

- name: Start and enable Flower service
  systemd:
    name: flower
    state: started
    enabled: yes