# roles/flower/tasks/main.yml

- name: Create virtual environment for Flower
  command: python3 -m venv {{ flower_virtualenv_path }}
  args:
    creates: "{{ flower_virtualenv_path }}/bin/activate"

- name: Install Flower in virtual environment
  pip:
    virtualenv: "{{ flower_virtualenv_path }}"
    name: flower
    state: present

- name: Deploy Flower systemd Service File
  template:
    src: flower.service.j2
    dest: /etc/systemd/system/flower.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon for Flower
  systemd:
    daemon_reload: yes

- name: Start and enable Flower service
  systemd:
    name: flower
    state: started
    enabled: yes

- name: Open port 5555 in firewalld for Flower
  firewalld:
    port: 5555/tcp
    permanent: yes
    state: enabled

- name: Reload firewalld to apply changes
  systemd:
    name: firewalld
    state: reloaded

