# /home/almalinux/ansible/playbooks/setup_celery_workers.yml

- name: Setup Celery Workers and Host
  hosts: workers, host
  become: yes
  vars:
    redis_host: "{{ hostvars['storage']['ansible_host'] }}"
    celery_user: "almalinux"
    celery_group: "almalinux"
    celery_bin: "/usr/local/bin/celery"  # Update the path based on where celery is installed
  tasks:
    - name: Install Python3 and pip
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Celery and Redis Python packages
      pip:
        name:
          - celery
          - redis
        state: present

    - name: Create data pipeline directory
      file:
        path: /opt/data_pipeline/
        state: directory
        owner: "{{ celery_user }}"
        group: "{{ celery_group }}"
        mode: '0755'

    - name: Deploy Celery Worker Script
      copy:
        dest: /opt/data_pipeline/celery_worker.py
        owner: "{{ celery_user }}"
        group: "{{ celery_group }}"
        mode: '0755'
        content: |
          from celery import Celery
          import subprocess
          import os

          # Define the Redis broker URL using Ansible variable
          app = Celery('celery_worker', broker='redis://{{ redis_host }}:6379/0')  

          @app.task
          def run_pipeline(input_dir, output_dir):
              """
              Celery task to run the data pipeline on a specified input directory.
              
              :param input_dir: Directory containing the input PDB files
              :param output_dir: Directory where output files will be saved
              """
              pipeline_script = "/opt/data_pipeline/pipeline_script.py"
              cmd = [
                  "python3",
                  pipeline_script,
                  input_dir,
                  output_dir
              ]
              try:
                  process = subprocess.run(cmd, capture_output=True, text=True, check=True)
                  return {
                      'stdout': process.stdout,
                      'stderr': process.stderr,
                      'returncode': process.returncode
                  }
              except subprocess.CalledProcessError as e:
                  return {
                      'stdout': e.stdout,
                      'stderr': e.stderr,
                      'returncode': e.returncode
                  }

    - name: Deploy Celery Service File
      copy:
        dest: /etc/systemd/system/celery.service
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Celery Service
          After=network.target

          [Service]
          Type=simple
          User={{ celery_user }}
          Group={{ celery_group }}
          WorkingDirectory=/opt/data_pipeline/
          ExecStart={{ celery_bin }} -A celery_worker worker --loglevel=info --concurrency=2
          Restart=always

          [Install]
          WantedBy=multi-user.target
        force: yes

    - name: Deploy Dispatch Tasks Script
      copy:
        dest: /opt/data_pipeline/dispatch_tasks.py
        owner: "{{ celery_user }}"
        group: "{{ celery_group }}"
        mode: '0755'
        content: |
          import sys
          from celery import Celery

          # Initialize Celery app with the Redis broker
          app = Celery('celery_worker', broker='redis://{{ redis_host }}:6379/0')

          if __name__ == "__main__":
              if len(sys.argv) != 3:
                  print("Usage: python3 dispatch_tasks.py [INPUT DIR] [OUTPUT DIRECTORY]")
                  sys.exit(1)

              input_dir = sys.argv[1]
              output_dir = sys.argv[2]
              result = app.send_task('celery_worker.run_pipeline', args=[input_dir, output_dir])
              print(f"Task {result.id} dispatched for {input_dir}")

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Celery service
      systemd:
        name: celery
        state: started
        enabled: yes

    - name: Ensure Celery worker script is executable
      file:
        path: /opt/data_pipeline/celery_worker.py
        mode: '0755'
