# /home/almalinux/ansible/playbooks/setup_celery_workers.yml

- name: Setup Celery Workers
  hosts: workers
  become: yes
  vars:
    redis_host: "{{ hostvars['storage']['ansible_host'] }}"
    celery_user: "almalinux"
    celery_group: "almalinux"
    celery_bin: "/usr/local/bin/celery"  # Updated to standard Celery binary path
  tasks:
    - name: Install Celery and Redis Python packages globally
      pip:
        name:
          - celery
          - redis
        state: present

    - name: Create data pipeline directory
      file:
        path: /opt/data_pipeline/
        state: directory
        owner: "{{ celery_user }}"
        group: "{{ celery_group }}"
        mode: '0755'

    - name: Deploy Updated Celery Worker Script
      copy:
        dest: /opt/data_pipeline/celery_worker.py
        owner: "{{ celery_user }}"
        group: "{{ celery_group }}"
        mode: '0755'
        content: |
          from celery import Celery
          import subprocess
          import os

          # Define the Redis broker URL
          app = Celery('celery_worker', broker='redis://{{ redis_host }}:6379/0')  

          @app.task
          def run_pipeline(input_dir, output_dir, organism):
              """
              Celery task to run the data pipeline on a specified input directory.
              
              :param input_dir: Path to the input .pdb file
              :param output_dir: Directory where output files will be saved
              :param organism: Organism type ('human' or 'ecoli')
              """
              pipeline_script = "/opt/data_pipeline/pipeline_script.py"
              cmd = [
                  "python3",
                  pipeline_script,
                  input_dir,
                  output_dir,
                  organism
              ]
              try:
                  process = subprocess.run(cmd, capture_output=True, text=True, check=True)
                  return {
                      'stdout': process.stdout,
                      'stderr': process.stderr,
                      'returncode': process.returncode
                  }
              except subprocess.CalledProcessError as e:
                  return {
                      'stdout': e.stdout,
                      'stderr': e.stderr,
                      'returncode': e.returncode
                  }

    - name: Deploy Updated Dispatch Tasks Script
      copy:
        dest: /opt/data_pipeline/dispatch_tasks.py
        owner: "{{ celery_user }}"
        group: "{{ celery_group }}"
        mode: '0755'
        content: |
          import sys
          from celery import Celery

          # Initialize Celery app with the Redis broker
          app = Celery('celery_worker', broker='redis://{{ redis_host }}:6379/0')

          if __name__ == "__main__":
              if len(sys.argv) != 4:
                  print("Usage: python3 dispatch_tasks.py [INPUT FILE] [OUTPUT DIRECTORY] [ORGANISM]")
                  sys.exit(1)

              input_file = sys.argv[1]
              output_dir = sys.argv[2]
              organism = sys.argv[3].lower()

              if organism not in ["human", "ecoli"]:
                  print("Error: ORGANISM must be either 'human' or 'ecoli'")
                  sys.exit(1)

              result = app.send_task('celery_worker.run_pipeline', args=[input_file, output_dir, organism])
              print(f"Task {result.id} dispatched for {input_file} with organism '{organism}'")

    - name: Deploy Celery Service File
      copy:
        dest: /etc/systemd/system/celery.service
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Celery Service
          After=network.target

          [Service]
          Type=simple
          User={{ celery_user }}
          Group={{ celery_group }}
          WorkingDirectory=/opt/data_pipeline/
          ExecStart={{ celery_bin }} -A celery_worker worker --loglevel=info --concurrency=4
          Restart=always

          [Install]
          WantedBy=multi-user.target
        force: yes

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Restart and enable Celery service
      systemd:
        name: celery
        state: restarted  # Use 'restarted' to apply any changes
        enabled: yes

    - name: Ensure Celery worker script is executable
      file:
        path: /opt/data_pipeline/celery_worker.py
        mode: '0755'
