---
- name: Cleanup Disk Space on All VMs
  hosts: all
  become: yes
  tasks:

    # Clean YUM/DNF cache if RedHat-based
    - name: Clean YUM/DNF cache if RedHat-based
      when: ansible_facts['pkg_mgr'] in ['dnf', 'yum']
      command: yum clean all
      ignore_errors: yes

    # Clean APT cache if Debian-based
    - name: Clean APT cache if Debian-based
      when: ansible_facts['pkg_mgr'] == 'apt'
      apt:
        autoclean: yes
        autoremove: yes
        clean: yes
      ignore_errors: yes

    # Remove root pip cache
    - name: Remove root pip cache
      file:
        path: "/root/.cache/pip"
        state: absent
      ignore_errors: yes

    # Remove user pip caches
    - name: Remove user pip caches
      shell: rm -rf /home/*/.cache/pip
      args:
        executable: /bin/bash
      ignore_errors: yes

    # Find log files over 100MB (100MB = 104857600 bytes)
    # Using +104857600 means strictly greater than 100MB in bytes
    - name: Find log files over 100MB
      find:
        paths: /var/log
        patterns: "*.log"
        recurse: yes
        size: "+104857600"
      register: large_logs
      ignore_errors: yes

    - name: Truncate large log files
      file:
        path: "{{ item.path }}"
        state: touch
        mode: '0644'
      loop: "{{ large_logs.files | default([]) }}"
      when: large_logs.matched|default(0) > 0
      ignore_errors: yes

    # Remove temporary files
    - name: Remove /tmp and /var/tmp files
      shell: rm -rf /tmp/* /var/tmp/*
      args:
        executable: /bin/bash
      ignore_errors: yes

    # Check disk usage after cleanup
    - name: Check disk usage after cleanup
      command: df -h
      register: disk_usage
      changed_when: false

    - name: Display disk usage
      debug:
        var: disk_usage.stdout_lines
