---
- name: Common configuration for all machines
  hosts: all
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update and upgrade yum packages
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install essential packages
      package:
        name:
          - git
          - vim
          - curl
          - wget
          - python3
          - python3-pip
        state: present

    - name: Install pip packages
      pip:
        name:
          - biopython
          - torch
          - numpy
          - scipy
          - faiss-cpu
        state: present
        executable: pip3
