- name: Deploy Pipeline Scripts to Worker Machines
  hosts: workers
  become: yes
  tasks:
    - name: Create pipeline directory on workers
      file:
        path: /opt/data_pipeline
        state: directory
        owner: almalinux
        group: almalinux
        mode: '0755'

    - name: Copy pipeline_script.py to workers
      copy:
        src: /home/almalinux/ansible/playbooks/pipeline_script.py
        dest: /opt/data_pipeline/pipeline_script.py
        owner: almalinux
        group: almalinux
        mode: '0755'

    - name: Copy results_parser.py to workers
      copy:
        src: /home/almalinux/ansible/playbooks/results_parser.py
        dest: /opt/data_pipeline/results_parser.py
        owner: almalinux
        group: almalinux
        mode: '0755'
