- name: Download and Extract Datasets on NFS Server
  hosts: storage
  become: yes

  tasks:
    - name: Install required packages
      dnf:
        name:
          - wget
          - tar
        state: present

    - name: Download Human Proteome Dataset
      get_url:
        url: https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000005640_9606_HUMAN_v4.tar
        dest: /mnt/datasets/UP000005640_9606_HUMAN_v4.tar
        mode: '0644'
      register: download_human

    - name: Ensure destination directory exists for Human Proteome
      file:
        path: /mnt/datasets/human_proteome
        state: directory
      when: download_human.changed or not download_human.changed

    - name: Extract Human Proteome Dataset
      unarchive:
        src: /mnt/datasets/UP000005640_9606_HUMAN_v4.tar
        dest: /mnt/datasets/human_proteome
        remote_src: yes
      when: download_human.changed

    - name: Download E.coli Proteome Dataset
      get_url:
        url: https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000000625_83333_ECOLI_v4.tar
        dest: /mnt/datasets/UP000000625_83333_ECOLI_v4.tar
        mode: '0644'
      register: download_ecoli

    - name: Ensure destination directory exists for E.coli Proteome
      file:
        path: /mnt/datasets/ecoli_proteome
        state: directory
      when: download_ecoli.changed or not download_ecoli.changed

    - name: Extract E.coli Proteome Dataset
      unarchive:
        src: /mnt/datasets/UP000000625_83333_ECOLI_v4.tar
        dest: /mnt/datasets/ecoli_proteome
        remote_src: yes
      when: download_ecoli.changed

    - name: Download CATH Foldclass Database
      get_url:
        url: http://bioinfadmin.cs.ucl.ac.uk/downloads/merizo_search/cath_foldclassdb.tar.gz
        dest: /mnt/datasets/cath_foldclassdb.tar.gz
        mode: '0644'
      register: download_cathdb

    - name: Ensure destination directory exists for CATH Foldclass DB
      file:
        path: /mnt/datasets/cath_foldclassdb
        state: directory
      when: download_cathdb.changed or not download_cathdb.changed

    - name: Extract CATH Foldclass Database
      unarchive:
        src: /mnt/datasets/cath_foldclassdb.tar.gz
        dest: /mnt/datasets/cath_foldclassdb
        remote_src: yes
      when: download_cathdb.changed
