---
- name: Extract and Prepare Datasets on Storage Server
  hosts: storage
  become: yes

  vars:
    datasets_dir: /mnt/datasets
    human_tarball: "{{ datasets_dir }}/UP000005640_9606_HUMAN_v4.tar"
    ecoli_tarball: "{{ datasets_dir }}/UP000000625_83333_ECOLI_v4.tar"
    human_proteome_dir: "{{ datasets_dir }}/human_proteome"
    ecoli_proteome_dir: "{{ datasets_dir }}/ecoli_proteome"

  tasks:
    - name: Ensure directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ human_proteome_dir }}"
        - "{{ ecoli_proteome_dir }}"

    - name: Check if Human Proteome is extracted
      stat:
        path: "{{ human_proteome_dir }}/extracted.flag"
      register: human_flag

    - name: Extract Human Proteome
      unarchive:
        src: "{{ human_tarball }}"
        dest: "{{ human_proteome_dir }}"
        remote_src: yes
      when: not human_flag.stat.exists

    - name: Create extracted flag file for Human Proteome
      file:
        path: "{{ human_proteome_dir }}/extracted.flag"
        state: touch
      when: not human_flag.stat.exists

    - name: Check if E.coli Proteome is extracted
      stat:
        path: "{{ ecoli_proteome_dir }}/extracted.flag"
      register: ecoli_flag

    - name: Extract E.coli Proteome
      unarchive:
        src: "{{ ecoli_tarball }}"
        dest: "{{ ecoli_proteome_dir }}"
        remote_src: yes
      when: not ecoli_flag.stat.exists

    - name: Create extracted flag file for E.coli Proteome
      file:
        path: "{{ ecoli_proteome_dir }}/extracted.flag"
        state: touch
      when: not ecoli_flag.stat.exists

    - name: Set permissions on extracted directories
      file:
        path: "{{ item }}"
        owner: almalinux
        group: almalinux
        mode: '0755'
        recurse: yes
      loop:
        - "{{ human_proteome_dir }}"
        - "{{ ecoli_proteome_dir }}"
