---
- name: Extract original datasets
  hosts: storage  # Or master if not using separate storage
  become: yes
  vars:
    datasets_dir: /mnt/datasets
    human_tar: "{{ datasets_dir }}/UP000005640_9606_HUMAN_v4.tar"
    ecoli_tar: "{{ datasets_dir }}/UP000000625_83333_ECOLI_v4.tar"
  tasks:
    - name: Extract Human Proteome dataset
      unarchive:
        src: "{{ human_tar }}"
        dest: "{{ datasets_dir }}/"
        remote_src: yes
      when: human_tar is file

    - name: Extract E.coli Proteome dataset
      unarchive:
        src: "{{ ecoli_tar }}"
        dest: "{{ datasets_dir }}/"
        remote_src: yes
      when: ecoli_tar is file
