- name: Install Dependencies on Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Install required packages
      package:
        name:
          - python3
          - python3-pip
          - pigz
          - git
        state: present

    - name: Upgrade pip
      pip:
        name: pip
        executable: pip3
        state: latest

    - name: Uninstall existing torch if present
      pip:
        name: torch
        state: absent
        executable: pip3

    - name: Install required Python packages via pip (excluding torch)
      pip:
        name:
          - pandas
          - numpy
          - biopython
          - scipy
          - faiss-cpu
        executable: pip3
        state: present

    - name: Install CPU-only PyTorch
      pip:
        name: torch
        executable: pip3
        state: present
        extra_args: "--index-url https://download.pytorch.org/whl/cpu"

    - name: Clone Merizo Search Repository
      git:
        repo: https://github.com/psipred/merizo_search.git
        dest: /opt/merizo_search
        version: main
        force: yes

    - name: Install Merizo Search Dependencies
      pip:
        requirements: /opt/merizo_search/merizo_search/programs/Merizo/requirements.txt
        state: present
        executable: pip3

    - name: Make merizo.py Executable
      file:
        path: /opt/merizo_search/merizo_search/merizo.py
        mode: '0755'
        owner: almalinux
        group: almalinux

    - name: Set Environment Variable for Merizo Search
      lineinfile:
        path: /home/almalinux/.bashrc
        line: 'export MERIZO_HOME=/opt/merizo_search'
        create: yes
        state: present

    - name: Verify PyTorch Installation
      command: python3 -c "import torch; print(torch.__version__); print(torch.cuda.is_available())"
      register: torch_check
      changed_when: false

    - name: Display PyTorch Installation Details
      debug:
        msg: "PyTorch Version: {{ torch_check.stdout_lines[0] }}, CUDA Available: {{ torch_check.stdout_lines[1] }}"
