- name: Install Dependencies on Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Install required packages
      package:
        name:
          - python3
          - python3-pip
          - pigz
          - git
        state: present

    - name: Install required Python packages via pip
      pip:
        name:
          - pandas
          - numpy
          - biopython
          - scipy
          - faiss-cpu
          - torch
        executable: pip3
        state: present

    - name: Clone Merizo Search Repository
      git:
        repo: https://github.com/psipred/merizo_search.git
        dest: /opt/merizo_search
        version: main
        force: yes

    - name: Install Merizo Search Dependencies
      pip:
        requirements: /opt/merizo_search/merizo_search/programs/Merizo/requirements.txt
        state: present
        executable: pip3

    - name: Make merizo.py Executable
      file:
        path: /opt/merizo_search/merizo_search/merizo.py
        mode: '0755'
        owner: almalinux
        group: almalinux

    - name: Create Symlink for CATH Foldclass Database
      file:
        src: /mnt/datasets/cath_foldclassdb
        dest: /home/almalinux/merizo_search/examples/database/cath-4.3-foldclassdb
        state: link
        owner: almalinux
        group: almalinux

    - name: Set Environment Variable for Merizo Search
      lineinfile:
        path: /home/almalinux/.bashrc
        line: 'export MERIZO_HOME=/opt/merizo_search'
        create: yes
        state: present

- name: Install Dependencies on Storage Node
  hosts: storage
  become: yes
  tasks:
    - name: Install EPEL repository (for pigz)
      yum:
        name: epel-release
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install required packages
      dnf:
        name:
          - wget
          - tar
          - pigz
        state: present
