- import_playbook: common.yml
- import_playbook: install_dependencies.yml
- import_playbook: nfs_server.yml
- import_playbook: nfs_clients.yml
- import_playbook: download_and_prepare_datasets.yml
- import_playbook: uncompress_files.yml
- import_playbook: deploy_scripts.yml
- import_playbook: run_pipeline.yml
