---
- name: Setup Monitoring and Logging
  hosts: all
  become: yes
  tasks:
    #### Install Prometheus Node Exporter
    - name: Install Prometheus Node Exporter
      block:
        - name: Download Node Exporter binary
          get_url:
            url: "https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz"
            dest: "/tmp/node_exporter.tar.gz"

        - name: Extract Node Exporter
          unarchive:
            src: "/tmp/node_exporter.tar.gz"
            dest: "/tmp/"
            remote_src: yes

        - name: Move Node Exporter binary to /usr/local/bin/
          command: mv /tmp/node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin/
          args:
            creates: /usr/local/bin/node_exporter

        - name: Ensure Node Exporter binary is executable
          file:
            path: /usr/local/bin/node_exporter
            mode: '0755'

        - name: Create Node Exporter service
          copy:
            dest: /etc/systemd/system/node_exporter.service
            content: |
              [Unit]
              Description=Node Exporter
              After=network.target

              [Service]
              User=root
              ExecStart=/usr/local/bin/node_exporter
              Restart=always

              [Install]
              WantedBy=multi-user.target

        - name: Reload systemd daemon for Node Exporter
          systemd:
            daemon_reload: yes

        - name: Start and enable Node Exporter service
          systemd:
            name: node_exporter
            state: started
            enabled: yes

    #### Install and Configure Grafana (Control Node Only)
    - name: Install and Configure Grafana on Control Node
      hosts: localhost
      become: yes
      tasks:
        - name: Add Grafana repository
          yum_repository:
            name: grafana
            description: Grafana Repository
            baseurl: https://packages.grafana.com/oss/rpm
            gpgcheck: yes
            gpgkey: https://packages.grafana.com/gpg.key
            enabled: yes

        - name: Install Grafana
          yum:
            name: grafana
            state: present

        - name: Install initscripts package (for systemd-sysv-install)
          yum:
            name: initscripts
            state: present

        # Removed the task that creates the custom Grafana service file

        - name: Reload systemd daemon
          systemd:
            daemon_reload: yes

        - name: Ensure Grafana directories have correct ownership
          file:
            path: "{{ item }}"
            state: directory
            owner: grafana
            group: grafana
            recurse: yes
          loop:
            - /var/lib/grafana
            - /var/log/grafana
            - /etc/grafana

        - name: Start and enable Grafana service
          systemd:
            name: grafana-server
            state: started
            enabled: yes

        - name: Fetch Grafana service logs
          shell: journalctl -u grafana-server -b --no-pager
          register: grafana_logs
          ignore_errors: yes

        - name: Display Grafana service logs
          debug:
            var: grafana_logs.stdout

    #### Configure Logging
    - name: Configure Logging
      block:
        - name: Install rsyslog
          yum:
            name: rsyslog
            state: present

        - name: Configure rsyslog to send logs to control node
          lineinfile:
            path: /etc/rsyslog.conf
            regexp: '^\*\.\*'
            line: "*.* @@localhost:514"  # Replace 'localhost' with control node IP if needed
            state: present

        - name: Restart rsyslog
          systemd:
            name: rsyslog
            state: restarted
