---
- name: Distribute and Run Data Analysis Pipeline via Celery
  hosts: control-node
  become: yes
  vars:
    data_input_dir: "/mnt/datasets/human_proteome/"
    results_dir: "/mnt/results/"
  tasks:
    - name: Find all .pdb files
      find:
        paths: "{{ data_input_dir }}"
        patterns: "*.pdb"
      register: pdb_files

    - name: Deploy dispatch_tasks.py to control node
      copy:
        src: files/dispatch_tasks.py
        dest: /opt/data_pipeline/dispatch_tasks.py
        mode: '0755'

    - name: Enqueue pipeline tasks
      shell: |
        python3 /opt/data_pipeline/dispatch_tasks.py "{{ item.path }}" "{{ results_dir }}"
      loop: "{{ pdb_files.files }}"
      when: pdb_files.matched > 0
