---
- name: Set Up Worker Nodes
  hosts: workers
  become: yes

  vars:
    data_input_dir: "/mnt/datasets/human_proteome/"

  tasks:
    - name: Install required packages
      package:
        name:
          - python3
          - python3-pip
          - pigz
        state: present

    - name: Install required Python packages
      pip:
        name:
          - pandas
          - numpy
          - biopython
          - scipy
          - faiss-cpu
          - torch
        executable: pip3

    - name: Uncompress .pdb.gz files using pigz
      shell: "pigz -d -k -p {{ ansible_processor_vcpus }} *.pdb.gz"
      args:
        chdir: "{{ data_input_dir }}"

