- name: Uncompress .pdb.gz and .cif.gz Files Using pigz
  hosts: storage
  become: yes
  vars:
    datasets_dirs:
      - /mnt/datasets/human_proteome
      - /mnt/datasets/ecoli_proteome
    parallel_jobs: 4  # Adjust based on CPU cores
  tasks:
    - name: Uncompress all .gz files using pigz
      shell: |
        find {{ item }} -type f \( -name "*.pdb.gz" -o -name "*.cif.gz" \) -print0 | xargs -0 -n 1 -P {{ parallel_jobs }} pigz -d -f
      loop: "{{ datasets_dirs }}"
      args:
        executable: /bin/bash
      tags: uncompress_files

    - name: Verify uncompression by counting original files
      find:
        paths: "{{ item }}"
        patterns:
          - "*.pdb"
          - "*.cif"
        recurse: yes
        file_type: file
      loop: "{{ datasets_dirs }}"
      register: original_files
      tags: verify_uncompression

    - name: Debug - Number of uncompressed files
      debug:
        msg: "Total number of uncompressed files in {{ item }}: {{ original_files.results[loop.index0].matched }}"
      loop: "{{ datasets_dirs }}"
      tags: debug