#cloud-config
users:
  - name: almalinux
    home: /home/almalinux
    shell: /bin/bash
    groups: sudo
    ssh_authorized_keys:
      - ${public_key_1}
      - ${public_key_2}
      - ${public_key_3}
